version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: payroll-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build: .
    container_name: payroll-app
    depends_on:
      - mysql
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    restart: always

volumes:
  mysql_data: